[project]
name = "day-04"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax==0.5.0",
    "jax-metal>=0.1.1",
    "jaxlib==0.5.0",
]
